### ISSUE TITLE
aimodeURL and other meta data to casestructure

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeAPI#20]
/:id/casestructure needs to be updated to include AI Model URL and other metadata in JSON format in the case structure under 
"hasCaseStructureMetaData" predicate (added to case-structure.json under AIModel)
this is used by the chatbot to communicate with AI model and explainer libraries.

**Comment by chamathpali** [comment]
#24

**Comment by chamathpali** [comment]
https://github.com/isee4xai/iSeeAPI/pull/24/files#diff-967d19abbfa3779ea5ccd0aec525411463743d9298ef9d47230fe80a4a450f80R172
