### ISSUE TITLE
save chat history + evaluation question results

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeAPI#34]

**Comment by anjanaw** [comment]
json to expect is 
![Screenshot 2023-05-15 at 15 11 21](https://github.com/isee4xai/iSeeAPI/assets/233262/2ad98ae2-8628-4b32-b6bf-cee8940c408d)

**Comment by chamathpali** [comment]
API is ready - can you pass it like this:
```
{
    "interaction": { "nodes" ... , "executions":.... },
    "usecase_version": 1
}
```
